Assignment 1/config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Assignment 1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Assignment 1/app/models/course.rb
class Course < ApplicationRecord
  has_many :section
end

Assignment 1/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
end

Assignment 1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
protect_from_forgery with: :exception

  
before_action :cors_preflight_check
  
after_action :cors_set_access_control_headers


# https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

# If this is a preflight OPTIONS request, then short-circuit the
# request, return only the necessary headers and return an empty

# text/plain.

  
def cors_preflight_check
    
if request.method == :options
      
headers['Access-Control-Allow-Origin'] = '*'

    
end
  
end


# For all responses in this controller, return the CORS access control headers.

  
def cors_set_access_control_headers
    
headers['Access-Control-Allow-Origin'] = '*'
    
headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
  
end


end

Assignment 1/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :department, :course_number, :hours)
    end
end

Assignment 1/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:semester, :section_number, :course_id, :room)
    end
end

Assignment 1/app/helpers/application_helper.rb
module ApplicationHelper
end

Assignment 1/app/helpers/courses_helper.rb
module CoursesHelper
end

Assignment 1/app/helpers/sections_helper.rb
module SectionsHelper
end

Assignment 1/app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label :course_number %>
    <%= form.text_field :course_number %>
  </div>

  <div class="field">
    <%= form.label :hours %>
    <%= form.text_field :hours %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Assignment 1/app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

Assignment 1/app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Druidia University</h1>

<h2>"Churning out pushovers and sissies for thousands of years."</h2>

<h3>Courses</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th>Course number</th>
      <th>Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.department %></td>
        <td><%= course.course_number %></td>
        <td><%= course.hours %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

Assignment 1/app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

Assignment 1/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @course.department %>
</p>

<p>
  <strong>Course number:</strong>
  <%= @course.course_number %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @course.hours %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

Assignment 1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebAppDevelopment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Assignment 1/app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :semester %>
    <%= form.text_field :semester %>
  </div>

  <div class="field">
    <%= form.label :section_number %>
    <%= form.text_field :section_number %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.collection_select :course_id, Course.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :room %>
    <%= form.text_field :room %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Assignment 1/app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

Assignment 1/app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Druidia University</h1>

<h2>"Churning out pushovers and sissies for thousands of years."</h2>

<h3>Sections</h3>

<table>
  <thead>
    <tr>
      <th>Semester</th>
      <th>Section number</th>
      <th>Course</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.semester %></td>
        <td><%= section.section_number %></td>
        <td><%= section.course.name %></td>
        <td><%= section.room %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

Assignment 1/app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

Assignment 1/app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Semester:</strong>
  <%= @section.semester %>
</p>

<p>
  <strong>Section number:</strong>
  <%= @section.section_number %>
</p>

<p>
  <strong>Course:</strong>
  <%= @section.course.name %>
</p>

<p>
  <strong>Room:</strong>
  <%= @section.room %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>